export const columns = [
  { key: "time", label: "زمان" },
  { key: "l18", label: "نماد" },
  { key: "l30", label: "نام شرکت" },
  { key: "cs", label: "گروه صنعت" },
  { key: "mv", label: "ارزش بازار" },
  { key: "eps", label: "EPS" },
  { key: "pe", label: "P/E" },
  { key: "tmin", label: "آستانه پایین" },
  { key: "tmax", label: "آستانه بالا" },
  { key: "plp", label: "٪ تغییر آخرین" },
  { key: "pcp", label: "٪ تغییر پایانی" },
  { key: "tvol", label: "حجم معاملات" },
  { key: "tval", label: "ارزش معاملات" },
  { key: "Buy_CountI", label: "خریدار حقیقی" },
  { key: "Buy_CountN", label: "خریدار حقوقی" },
  { key: "Sell_CountI", label: "فروشنده حقیقی" },
  { key: "Sell_CountN", label: "فروشنده حقوقی" },
  { key: "Buy_I_Volume", label: "حجم خرید حقیقی" },
  { key: "Buy_N_Volume", label: "حجم خرید حقوقی" },
  { key: "Sell_I_Volume", label: "حجم فروش حقیقی" },
];